import React, { useState } from 'react';
import {
  X,
  Printer,
  Download,
  ExternalLink,
  Check,
  FileText,
  AlertCircle
} from 'lucide-react';
import {
  PrintReportOptions,
  generateReportHtml,
  downloadReportPdf,
  openReportInNewTab,
  printStructuredReport
} from '../../utils/printReport';

interface ReportPrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  options: PrintReportOptions | null;
}

export const ReportPrintModal: React.FC<ReportPrintModalProps> = ({
  isOpen,
  onClose,
  options
}) => {
  const [isPdfGenerating, setIsPdfGenerating] = useState(false);
  const [isPdfDownloaded, setIsPdfDownloaded] = useState(false);

  if (!isOpen || !options) return null;

  const handlePrint = () => {
    printStructuredReport(options);
  };

  const handleOpenNewWindow = () => {
    openReportInNewTab(options);
  };

  const handleDownloadPdf = () => {
    setIsPdfGenerating(true);
    try {
      downloadReportPdf(options);
      setIsPdfDownloaded(true);
      setTimeout(() => setIsPdfDownloaded(false), 3000);
    } catch (e) {
      console.error('PDF export failed:', e);
    } finally {
      setIsPdfGenerating(false);
    }
  };

  const htmlContent = generateReportHtml(options);

  return (
    <div
      id="report-print-preview-modal"
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 backdrop-blur-xs p-4 overflow-y-auto"
    >
      <div className="relative w-full max-w-5xl bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden my-6 flex flex-col max-h-[92vh]">
        {/* Header Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-50 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-800 flex items-center justify-center shadow-xs">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-extrabold text-slate-900">
                  {options.title}
                </h3>
                <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 font-bold text-[10px] rounded-full uppercase">
                  Print & PDF Preview
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                Audit Period: <strong className="text-slate-700">{options.dateRangeLabel || 'All Records'}</strong> • Generated by {options.generatedBy || 'Authorized Staff'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleOpenNewWindow}
              className="inline-flex items-center px-3 py-1.5 text-xs font-bold text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 rounded-xl transition-colors cursor-pointer shadow-2xs"
              title="Open standalone printable page in a new browser tab (bypasses iframe restrictions)"
            >
              <ExternalLink className="w-3.5 h-3.5 mr-1.5 text-blue-600" />
              Open in New Tab
            </button>

            <button
              type="button"
              onClick={handleDownloadPdf}
              disabled={isPdfGenerating}
              className="inline-flex items-center px-3.5 py-1.5 text-xs font-bold text-white bg-slate-900 hover:bg-slate-800 rounded-xl transition-colors cursor-pointer shadow-xs disabled:opacity-50"
            >
              {isPdfDownloaded ? (
                <>
                  <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-400" />
                  PDF Saved!
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  {isPdfGenerating ? 'Generating...' : 'Download PDF'}
                </>
              )}
            </button>

            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center px-4 py-1.5 text-xs font-bold text-white bg-emerald-700 hover:bg-emerald-800 rounded-xl transition-colors cursor-pointer shadow-xs"
            >
              <Printer className="w-3.5 h-3.5 mr-1.5" />
              Print Document
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-xl transition-colors cursor-pointer ml-1"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Live Document Preview */}
        <div className="flex-1 p-6 overflow-y-auto bg-slate-100/70">
          <div className="max-w-[850px] mx-auto bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden">
            <div
              className="p-8 font-sans text-slate-900"
              dangerouslySetInnerHTML={{
                __html: htmlContent
                  .replace(/<!DOCTYPE html>[\s\S]*?<body[^>]*>/i, '')
                  .replace(/<\/body>[\s\S]*?<\/html>/i, '')
              }}
            />
          </div>
        </div>

        {/* Footer info bar */}
        <div className="flex items-center justify-between px-6 py-3 border-t border-slate-200 bg-slate-50 text-xs text-slate-500 flex-shrink-0">
          <div className="flex items-center gap-1.5 text-emerald-800 font-medium">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Official Regulatory Audit Document formatted according to Ghana Pharmacy Council standards
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-1.5 text-xs font-bold text-slate-600 hover:text-slate-800 hover:bg-slate-200 rounded-xl transition-colors cursor-pointer"
            >
              Close
            </button>
            <button
              type="button"
              onClick={handlePrint}
              className="px-4 py-1.5 text-xs font-bold text-white bg-emerald-700 hover:bg-emerald-800 rounded-xl transition-colors cursor-pointer"
            >
              Print Now
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
